[package]
name = "winterfox-service"
version = "0.1.0"
authors = [ "SuYufox" ]
description = "SuYufox's Toolbox Service"
edition = "2021"
rust-version = "1.77.2"
exclude = ["/examples", "/dist-js", "/guest-js", "/node_modules"]
links = "winterfox-service"

[dependencies]
tauri = { version = "2.10.0" }
serde = "1.0"
thiserror = "2"
winterfox-plugins = { path = "../plugins" }
winterfox-configs = { path = "../configs" }

[build-dependencies]
tauri-plugin = { version = "2.5.3", features = ["build"] }
