[package]
name = "winterfox-service"
version = "0.1.0"
authors = [ "SuYufox" ]
description = "SuYufox's Toolbox Service"
edition = "2021"
rust-version = "1.77.2"
exclude = ["/examples", "/dist-js", "/guest-js", "/node_modules"]
links = "winterfox-service"

[dependencies]
tauri = { version = "2.10.0" }
serde = "1.0"
thiserror = "2"
winterfox-plugins = { path = "../plugins" }
winterfox-configs = { path = "../configs" }
log = "0.4.29"
chrono = "0.4.43"
schemars = "0.8"
FreedomLogger = { git = "https://github.com/Jurgen-Be/FreedomLogger.git", version = "1.1.0" }

[build-dependencies]
schemars = "0.8"
tauri-plugin = { version = "2.5.3", features = ["build"] }
