[package]
name = "winterfox-cli"
version = "0.1.0"
edition = "2021"
description = "Winterfox CLI - A powerful CLI tool for Winterfox project management"
license = "MIT"
authors = ["Suyufox <suyufox@example.com>"]
repository = "https://github.com/suyufox/winterfox"
homepage = "https://github.com/suyufox/winterfox"
readme = "README.md"
keywords = ["cli", "rust", "winterfox", "tauri", "desktop", "cross-platform"]
categories = ["command-line-utilities", "development-tools"]

[[bin]]
name = "winfox"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5.60", features = ["derive"] }
