[package]
name = "winterfox-configs"
version = "0.1.0"
authors = [ "You" ]
description = "SuYufox's Toolbox Configs"
edition = "2021"
rust-version = "1.77.2"
exclude = ["/examples", "/dist-js", "/guest-js", "/node_modules"]
links = "winterfox-configs"

[dependencies]
tauri = { version = "2.10.0" }
serde = "1.0"
thiserror = "2"
schemars = "0.8"

[build-dependencies]
schemars = "0.8"
tauri-plugin = { version = "2.5.3", features = ["build"] }
